require_relative "politburo/support"
require_relative "politburo/version"
require_relative "politburo/dependencies"
require_relative "politburo/dsl"
require_relative "politburo/resource"
require_relative "politburo/tasks"
require_relative "politburo/cli"
